[build]
  publish = "public"
  functions = "netlify/functions"

[context.production]
  SITE_ID = "fabbe670-8c12-4ab5-b7e2-8daefd3b0121"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
